### ISSUE TITLE
org-brain-new-child created entries in the wrong place

### ISSUE THREAD

**Issue by lbgaml** [Kungsgeten/org-brain#119] opened 2018-07-06 00:51 UTC
Hi Kungsgeten,

Thanks very much for the amazing package. It's become an important part of my knowledge management workflow.

I have found that when calling org-brain-new-child from the visualiser the headline often get created in the wrong place in my brain file and I have to manually refile it. But it is an inconsistent bug.

For example, I was in the category "creation" in my brain file and tried to create a category "creational heresies." This was created in the wrong spot. I manually refiled it and then the next categories I tried to create were created in the appropriate location. Just to see what would happen I tried to create another "creational heresies" child and this time it was put in the right place.

Let me know if you need more information.

**Comment by Kungsgeten** [comment] 2018-07-17 16:40
Hi! Sorry for the late response.

I've also noticed this behaviour sometimes, but like for you it is inconsistent. I'm not really sure why/when it happens. My guess is that it might have something to do with already opened files, and perhaps narrowing or the folding of the headlines.

If you find some steps to recreate it, I would be grateful.

**Comment by lbgaml** [comment] 2018-08-04 05:10
No problem. I'll keep my eyes open.

**Comment by Anton-Latukha** [comment] 2018-11-11 14:47
I am observing carefully now.

It misplaces child placement even when the org file was not opened (was opening only org-agenda TODO view).

Org-brain seems to insert child under the last node I created/was working with.

**Comment by Anton-Latukha** [comment] 2018-11-26 19:37
Yep. Not even opening myself `org` file.

Org-brain seems to insert child to the wrong parent like this:
```org
...
* Root #N
** Target parent
** [1..N] of other entries
** Wrong parent
*** [1..N] of its children
*** <- entry placed here
* Root #N+1
...
```

**Comment by Kungsgeten** [comment] 2018-11-26 20:37
Thanks @Anton-Latukha! I'll see if I can recreate it, and hopefully understand why this happens.

**Comment by ZacheryPD** [comment] 2019-01-05 01:33
I can reasonably consistently reproduce this issue with links.  

1. open an org file with multiple children in it.  (i.e. my course has headline child entries for each paper I am reading).
2. Position the cursor inside a child entry with the brain buffer and org file open in a split view (so org-brain is on the left and the org file in question is on the right with the cursor positioned in the document somewhere). 
3. Switch focus to the org-brain window and press 'l' to add a link.
4. The link will be added at the cursor's location. 

The same does not happen if I simply close the org file window.  Not sure what the fix is, but this is pretty consistent for me at the moment.

**Comment by Kungsgeten** [comment] 2019-01-10 23:36
Sorry for taking so long to fix this. I experimented a bit and managed to recreate it, using the example from @Anton-Latukha . I've committed a small change, which I hope solves the problem (it did for me).

I am not sure if this is related to the problem with resources/links.

**Comment by Anton-Latukha** [comment] 2019-01-11 23:14
@Kungsgeten 
Appreciate you doing it very much.

**Comment by Kungsgeten** [comment] 2019-03-22 07:53
@lbgaml @Anton-Latukha I'm marking this as closed for now, since I think the problem has been solved. If you still have problems, please reopen.

**Closed by Kungsgeten** 2019-03-22 07:53 UTC
Labels: bug

**Comment by Anton-Latukha** [comment] 2019-03-22 18:41
Indeed, the `org-brain` now works well.
And I can not close issue, anyway :)
Thank you.
