### ISSUE TITLE
Error: org-back-to-heading: Before first headline at position 1 in buffer...

### ISSUE THREAD

**Issue by ghost** [Kungsgeten/org-brain#110] opened 2018-05-18 14:59 UTC
I'm unable to reproduce this, but I've seen this error after working on an `org-brain` buffer for a while...  
I couldn't activate visualized mode any more (this error), and had to restart Emacs. 

```sh
org-back-to-heading: Before first headline at position 1 in buffer  *temp*-630161
```

**Comment by Kungsgeten** [comment] 2018-05-22 14:20
Okay, that's strange. The next time you encounter it, could you please try `M-x toggle-debug-on-error` and post the error message?

**Comment by AloisJanicek** [comment] 2018-06-04 06:33
`toggle-debug-on-error` is super useful!
I was getting exactly the same message too and it turned out that I had set some important org variables to `nil` while reorganizing my config.
So if anyone will ever encounter this message, make sure that you have set following vars to something other then nil:
```` lisp
  ;; (setq org-agenda-custom-commands nil)
  ;; (setq org-capture-templates nil)
  ;; (setq org-agenda-files nil)
  ;; (setq org-refile-targets nil)
````
(it is probably just `org-refile-targets`)

**Comment by Kungsgeten** [comment] 2018-06-04 11:30
@AloisJanicek It would be interesting to know why these variables trigger this error message. If you have saved an error log, please post it :)

**Comment by AloisJanicek** [comment] 2018-06-04 13:22
I am unable to reproduce it - this happens to me a lot with emacs :-) .
There was something there, in error message, about `org-refile-targets` and it made me remember about few org variables I set to `nil`.  
Now when I set them to nil, `org-brain` still works.  
So only thing I can is to confirm that I experienced this issue too while trying to visualize entry. But what exactly caused it and if it was org-brain's fault at all, still remains mystery.

**Comment by Kungsgeten** [comment] 2018-12-28 23:04
The issue could be because `org-mode` is trying to find an ID that doesn't exist in its cache. I had this error and did som debugging. Now there should be a better error message. Please keep me updated if you still get the "Before first headline" error.

**Comment by Kungsgeten** [comment] 2019-08-13 12:20
I haven't noticed this error in a long time. I'm marking it as closed for now, even though the error message that you should run `org-brain-update-id-locations` isn't the most elegant.

**Closed by Kungsgeten** 2019-08-13 12:20 UTC
Labels: bug
