### ISSUE TITLE
Adding link to file open do edit makes link appear in cursor location

### ISSUE THREAD

**Issue by srgkoshelev** [Kungsgeten/org-brain#143] opened 2019-01-06 03:58 UTC
With the same backstory as #142 I encountered issue with adding link to a file that is open for edit:
<img width="692" alt="screenshot 2019-01-05 21 55 19" src="https://user-images.githubusercontent.com/7409194/50731903-d4f04b00-1134-11e9-92f1-0e781fdb64aa.png">
<img width="692" alt="screenshot 2019-01-05 21 55 30" src="https://user-images.githubusercontent.com/7409194/50731904-d4f04b00-1134-11e9-8f0d-178ce4532ab1.png">

If the cursor is placed in a different place, link follows:
<img width="692" alt="screenshot 2019-01-05 21 56 30" src="https://user-images.githubusercontent.com/7409194/50731905-d4f04b00-1134-11e9-9784-6e234fee3f72.png">
<img width="692" alt="screenshot 2019-01-05 21 56 40" src="https://user-images.githubusercontent.com/7409194/50731906-d4f04b00-1134-11e9-8f1c-3f03ad3a303f.png">

**Comment by ZacheryPD** [comment] 2019-01-06 23:08
I think this is similar to the issue in #119

**Comment by srgkoshelev** [comment] 2019-01-07 15:30
It is definitely the same issue as the one you are describing but seems to be somewhat different to the initial #119. At least for me it is consistently reproducible.

**Comment by Kungsgeten** [comment] 2019-01-10 22:57
Hmm, I couldn't reproduce this. Did you try running `org-brain-update-id-locations` as instructed?

**Comment by srgkoshelev** [comment] 2019-01-11 04:06
I have just completed a full reinstall of spacemacs on both this and #142 persist. I suspect this is an issue on spacemacs' side.

Thank you for your response!

**Comment by Kungsgeten** [comment] 2019-08-13 12:09
I've mase some recent changes which I think might affect this. Could you please try again and see if the problem is still there?

**Comment by Kungsgeten** [comment] 2019-08-30 08:13
I'm fairly sure this is fixed now. I discovered the error and made a couple of commits which fixed it for me. Please re-open if it still occurs.

**Closed by Kungsgeten** 2019-08-30 08:13 UTC
Labels: bug
