### ISSUE TITLE
create children from `brain:` links in would-be parent (backlinks)

### ISSUE THREAD

**Issue by WillForan** [Kungsgeten/org-brain#46] opened 2017-06-22 01:54 UTC
I'd like inserting `brain:` links to automatically create a parent -> child relation a la backlinking ([where link is inserted] -> [where link points]).  

Initially I thought this was the work of `org-brain-insert-link.` But I can see how this would be unwanted behavior.
Is the right thing to create a function `org-brain-insert-childlink`?
Is it reasonable to use `buffer-file-name` and `org-brain-new-child`? 
It seems like it will be straightforward forward but i'm not yet up and running with `org-brain` or `elisp` and not sure where the dragons are. Any hints?

**Comment by Kungsgeten** [comment] 2017-06-22 06:28
Hi Will! I'm sorry to say I do not quite understand what behavior you are looking for. Could you please provide an example? Am I correct in assuming you want to insert links which link to the entry's parents? 

I'm in the final stages of rewriting org-brain from scratch, and the architecture of how child/parent relationships are represented has changed quite a bit. If you're just starting out using org-brain, I would advise you to wait until the new version is released.

**Comment by WillForan** [comment] 2017-06-23 01:20
Thanks for the quick response and the warning! I was just about to dive in :)

Having written out a few examples, I'm sure my initial issue is backwards. What I should shoot for is a method to create the relationship 
```
animal -> dog
```
by editing `animal.org` document to include the link `brain:dog` without touching `org-brain-visualize-mode`.  


My indention is to build a concept map in org-brain as if I were editing a personal wiki. I'd prefer this over `org-wiki` because the network relationships provide a way to traverse the graph in either direction (parent to child, or child to parent). We get backlinks for free.

**Comment by Kungsgeten** [comment] 2017-06-23 12:20
Okay, I see what you mean. The new version of `org-brain` is no longer using `brain:` links to define child-parent relationships. Instead it is using the local tree structure, or the `:PROPERTIES:` drawer to define relationships. However, there are two functions: `org-brain-goto-child` and `org-brain-goto-parent` which you can use in `org-mode` to choose and navigate to one of the children/parents. This is a bit like backlinking.

If you'd like you can read about the new version, and perhaps try it out, here: https://github.com/Kungsgeten/org-brain/tree/org-brain-id

There are a couple of bugs left, but I hope they'll be fixed in a couple of days *fingers crossed*.

**Comment by samspo** [comment] 2017-06-23 16:28
To follow up this discussion, just tried the new version.
I liked the way the older version worked and its simplicity. It gave the ability to create links directly in the text, in the exact place you want to link to something else. This is how a wiki works and why it is so powerful. What was powerful is that you added to the wiki feature the mindmap feature... and both were working together, was nice.
I understand the need for optimization, but I'm wondering if your not loosing something here...

**Comment by Kungsgeten** [comment] 2017-06-23 16:49
@samspo I agree, it is a powerful feature. I think I know of a way to solve it, in the new version: If adding a `brain:` link via `C-c C-l` (`org-insert-link`) or via `org-brain-insert-link` I think I could automate so that `org-brain` adds the child/parent properties when creating the link. By doing this, it would probably also be possible to write a function which scans all `org-brain` files for `brain:` links and add the correct properties, if missing. Such a function would make it easy to transfer an "old" setup to the new version, which is nice.

Do you think such a workflow could work? The downside is that the child/parent relationship would persist even if you remove the link, and it would not work if typing the link manually (only via `C-c C-l` or `org-brain-insert-link`).

**Comment by samspo** [comment] 2017-06-23 17:20
Would be a nice workaround. Especially the function which scans all org-brain files. Could also have a function that only scan the current buffer for links typed manually: the function could be used each time the buffer is saved, for example (We could even have "friends:" links that have the same behavior)

**Comment by Kungsgeten** [comment] 2017-06-24 16:43
Version 0.4 is now merged into master, please try the new version and see if it is okay. Otherwise please notify me on how you'd want the backlinking feature to work.

**Comment by mobotak** [comment] 2017-11-12 09:21
I'm sympathetic to the problem that comes up, especially in long issues, in which the original issue may have little to do (or perhaps be outdated or incorrect) after many comments have been posted, and so for someone new to the issue it takes a fair amount of time and synthesis to be clear on what the current state of the issue is. But as we said, I think the proposed change would be a change for the worse in most respects, especially for people who are already following an issue and are familiar with its current status.

https://mobotak.com/Categorygrid/id/80/%D8%A8%D8%A7%D8%AA%D8%B1%DB%8C%20%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84

**Comment by Kungsgeten** [comment] 2018-02-23 14:56
It is now possible to use `org-insert-link` (bound to `C-c C-l` by default) in an `org-brain` entry, in order to link to children (`brain-child:`), parents (`brain-parent:`), and friends (`brain-friend:`). Adding such a link in an entry will add this relationship. I think this is similar (or fill the same purpose) to the backlinking feature described in this issue, so I'm marking this as closed for the time being.

**Closed by Kungsgeten** 2018-02-23 14:56 UTC

**Comment by samspo** [comment] 2018-02-23 18:54
I like that feature. It is exactly what was missing for me. Thanks. 
Has org-brain-create-relationships-from-links been customized to take into account the different types of links that exist now? (in case I add links manually, sometimes)
I also think it would be wonderful to be able to customize the name of links (use child: instead of brain-child:, for  example)

**Comment by Kungsgeten** [comment] 2018-02-23 18:58
No, I haven't updated that function. That's probably something that I should do. Would you mind opening an issue for it? I don't know how easy it is to add the possibility of modifying the link names, but I could look into it.

**Comment by Kungsgeten** [comment] 2018-02-23 23:00
@samspo With the latest commit you can customize the names of the link types (not `brain:`, but the others) :)
