### ISSUE TITLE
Org-brain-visualize "|" wires mis-aligned with multiple parents

### ISSUE THREAD

**Issue by adam52** [Kungsgeten/org-brain#146] opened 2019-02-13 11:06 UTC
This is a follow up to issue #15. I installed the latest org-brain and can confirm that this issue still exists.

Here is my configuration.

### Packages

- Org-brain version 0.5
- GNU Emacs 26.1 (I have tested this on Emacs run from Terminal, installed from Homebrew, from Emacs for Mac OS X and from Emacs by Railwaycats)
- Org mode version 9.1.9 (9.1.9-elpaplus @ /Users/adamsneller/.emacs.d/elpa/org-plus-contrib-20180327/)

### Init file

    ;;; Add path to src directory
    (add-to-list 'load-path "~/.emacs.d/lisp")

    ;;; Set default org directory
    (setq default-directory "~/org/")

    ;;; Configure org-brain
    (require 'org-brain)
    (setq org-brain-path "~/org/brain")
    (setq org-id-track-globally t)
    (setq org-id-locations-file "~/.emacs.d/.org-id-locations")
    (setq org-brain-visualize-default-choices 'all)
    (setq org-brain-title-max-length 50)

### Results

![screen shot 2019-02-13 at 00 31 39](https://user-images.githubusercontent.com/1281353/52678115-661ec280-2f28-11e9-9ada-e6cadb73678a.jpg)

**Comment by adam52** [comment] 2019-02-16 22:41
On the off-chance that this had something to do with my Retina display, I installed Emacs/org-brain on an older iMac with the non-retinal display. Same issue.

![non-retina-display](https://user-images.githubusercontent.com/1281353/52906033-f10b0000-323b-11e9-8308-b1180dc6b467.png)

**Comment by Kungsgeten** [comment] 2019-03-05 13:53
Very strange, not sure why this happens.

**Comment by Kungsgeten** [comment] 2019-07-30 14:29
I've made a small change with the intent to fix another indentation issue (not sure if it works yet though). Maybe it also fixes this issue. Could you please report if this issue still remains?

**Comment by matthew-piziak** [comment] 2019-07-30 21:20
@Kungsgeten I can reproduce on 81e9903.
```

   Mid One   Mid Two
      |	|
      +----+----+
	   |
	   Common Child
```

**Comment by matthew-piziak** [comment] 2019-07-30 21:21
To reproduce:

In `DAGs.org`
```
#+BRAIN_PARENTS: Brain
* Mid Two
:PROPERTIES:
:ID:       9ea23aec-daf9-47de-ba99-c14fdc4cc2d6
:BRAIN_CHILDREN: Common%20Child
:END:
* Mid One
:PROPERTIES:
:ID:       4776ea19-0af7-43c5-8682-e40ed49e2cea
:BRAIN_CHILDREN: Common%20Child
:END:
```
In `Common Child.org`
```
#+BRAIN_PARENTS: 4776ea19-0af7-43c5-8682-e40ed49e2cea 9ea23aec-daf9-47de-ba99-c14fdc4cc2d6
```

**Comment by Kungsgeten** [comment] 2019-07-30 22:03
@matthew-piziak  Hmm, there seems to be tabs involved in the text you pasted. #184 mentions the variable `indent-tabs-mode`. I tried setting that variable to `t` in my init-file (was `nil`) and then I got some issues. I then added that `indent-tabs-mode` should be `nil` i the `org-brain` buffer, which fixed the problem.

I've pushed a tiny commit that I don't think should make a difference, but please see if it does. If it doesn't fix the problem, try adding `(setq-default indent-tabs-mode nil)` to your init-file and see if that changes anything.

**Comment by matthew-piziak** [comment] 2019-07-31 01:53
@Kungsgeten Fixed with `(setq-default indent-tabs-mode nil)`! :clap:

**Comment by matthew-piziak** [comment] 2019-07-31 01:53
```
   Mid One   Mid Two
      |         |
      +----+----+
           |
           V
     Common Child
```

Looks great.

**Comment by Kungsgeten** [comment] 2019-07-31 12:25
@matthew-piziak That's strange since I'm setting 'indent-tabs-mode` to `nil` already when running `org-brain-visualize`. Maybe I'll have to do it some other way.

**Comment by adam52** [comment] 2019-08-04 01:27
@Kungsgeten ah, you fixed it! It works great now - thank you!!

**Comment by hugovalk** [comment] 2019-08-10 12:11
As reporter of #184 I can say that I also had issues with multiple parents, but this is now fixed, probably with the indent-tab-mode fix. Everything renders fine now (as far as I can see).

**Comment by Kungsgeten** [comment] 2019-08-13 12:07
Closing this, as it seems to be fixed.

**Closed by Kungsgeten** 2019-08-13 12:07 UTC
Labels: bug
